# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Soo Story"

# A description of your site for social meta tag, search engines, and feed.xml
description: "I want to fix the pothole that's right in front of me before I fall in."

# Tagline near the site title
tagline: "Thoughts, stories and ideas."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://justgoodthemes.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guides
  url: /style-guide/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "J.S Ahn"
author_bio: "Software Developer, I love code."
author_url:  "http://findstar.pe.kr"
author_location: "South Korea"
author_image: /images/authorimage.png

# Sidebar Add banner
banner_url: "https://laravel.kr"
banner_image: images/laravel_kr_banner.png

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url:

# Social links in the site footer
twitter_username: "findstar"
facebook_username: "findstar"
github_username: "findstar"
linkedin_username: "findstar"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
